# (APPENDIX) Appendix {-} 

#  心得：老師授課 

## 第二週 陳衍任
2023-09-12


<button type="button" class="collapsible">地方稅法通則 第 2、3 條，氣候變遷因應法 第 28 條</button>
<div class="content">
  <p>

地方稅法通則 第 2 條
  
本通則所稱地方稅，指下列各稅：  
    一、財政收支劃分法所稱直轄市及縣（市）稅、臨時稅課。  
    二、地方制度法所稱直轄市及縣（市）特別稅課、臨時稅課及附加稅課。  
    三、地方制度法所稱鄉（鎮、市）臨時稅課。

---

地方稅法通則 第 3 條
  
I   直轄市政府、縣（市）政府、鄉（鎮、市）公所得視自治財政需要，依前條規定，開徵特別稅課、臨時稅課或附加稅課。但對下列事項不得開徵：  
        一、轄區外之交易。  
        二、流通至轄區外之天然資源或礦產品等。  
        三、經營範圍跨越轄區之公用事業。  
        四、損及國家整體利益或其他地方公共利益之事項。  
II  特別稅課及附加稅課之課徵年限至多四年，臨時稅課至多二年，年限屆滿仍需繼續課徵者，應依本通則之規定重行辦理。  
III 特別稅課不得以已課徵貨物稅或菸酒稅之貨物為課徵對象；臨時稅課應指明課徵該稅課之目的，並應對所開徵之臨時稅課指定用途，並開立專款帳戶。

---

氣候變遷因應法 第 28 條
  
I 中央主管機關為達成國家溫室氣體長期減量目標及各期階段管制目標，得分階段對下列排放溫室氣體之排放源徵收碳費：  
    一、直接排放源：依其排放量，向排放源之所有人徵收；其所有人非使用人或管理人者，向實際使用人或管理人徵收。  
    二、間接排放源：依其使用電力間接排放之排放量，向排放源之所有人徵收；其所有人非使用人或管理人者，向實際使用人或管理人徵收。  
II 生產電力之直接排放源，得檢具提供電力消費之排放量證明文件，向中央主管機關申請扣除前項第一款之排放量。  
III第一項碳費之徵收費率，由中央主管機關所設之費率審議會依我國溫室氣體減量現況、排放源類型、溫室氣體排放種類、排放量規模、自主減量情形及減量效果及其他相關因素審議，送中央主管機關核定公告，並定期檢討之。  
IV第一項碳費之徵收對象、計算方式、徵收方式、申報、繳費流程、繳納期限、繳費金額不足之追繳、補繳、收費之排放量計算方法、免徵及其他應遵行事項之辦法，由中央主管機關定之。

</p>
</div>
<br>



以下關於上課提到碳公課之徵收正當性做出回應：

上課中老師的問題，似乎是建立在，如果是地方針對碳交易或間接排放源課徵碳稅，是否會因為實際碳排放是發生在區域外，而不符合地方稅法通則第3條第一項之限制，而有正當性的疑問。學生認為，地方對於溫室氣體排放（包括間接）或碳權交易而課徵之稅、費（本文稱碳公課），並不會違反地方稅法通則第3條之限制。

依據事務之本質，若要對於（轄區外）碳交易課稅，則本就不屬於適宜以地方性管制作為依據之事項，事關碳交易本就屬於大尺度跨區域之事項，依賴區域性或全球性之龐大的交易體系，自非台灣的地方政府有權限或能力管轄得到之範圍。

若對於電力之使用，課徵間接的碳公課，也不會違反第3條第一項第三款。第三款之規範情形，是指，假設A地有河流，流通至B地，則A地不得對於B地使用此河流之水資源而課稅。
而對於電力之使用課徵碳公課之情形，原則上是針對A地轄區內之電力使用而課徵。以河流的例子對應，係B地針對在自己轄區內之水資源使用進行課稅，並無涉其河流之上游為誰。以發電設施（電力來源）為水源，則發電設施之所在地無權向位於他地的電力之實際使用者課徵碳公課。若作進一步的區別，條文所限制者為資源，而我們可以主張，我們是針對碳排放本質上作爲一種廣義上的污染而課稅，即不在條文所規範範圍内。

而至於A地對於在A地境内之電力使用課稅，其有一定的正當性。首先在名目上，以當今净零碳排的大趨勢之下，地方政府以此為公課對象，自有其合理性。而在法規範角度，若中央已開徵碳稅，則地方得依地方稅法通則第4條之規定而在限度内調高稅率。若非如此，地方或許也會以碳費之名目開徵，而特別公課之法律規範密度又是較低的。

但學生認爲，能否開徵此類碳公課，問題往往并非出在法規範層次，而是在於政治或地方經濟上的考量。地方政府若要開徵此類公課，未必能夠通過當地立法院三度程序。再回歸到碳公課之本質，或許應該先厘清其意義。財政需求與減碳目標都是長期的議題，也並非有了碳公課的徵收就能迎刃而解，而是應該綜合整體財政法制和環境保護法制而做長期的規劃。


---

## 第三週 蔡茂寅
2023-09-19


對於公共財政的意識，應該屬於公民意識中的重要部分。在一個成熟的公民社會中，人們透過公共參與進行與政府的互動實踐民主憲政。而公共財政事關公共收入與支出的分配，特別在支出面涉及到對於行政機關的監督與制衡，因而公共財政意識的教育將有利於民主憲政與法治國的落實。稅捐作為主要的公共收入來源，是首先需要加強認識的項目。若要培養納稅人意識，除了稅捐遵從的教育，應該整體地讓納稅人認識到，他們有權利去瞭解和監督公共支出的分配方式（就好像上課時講到的英國皇室向貴族課稅時一樣。我想，當人們對於公共支出（公共建設、社會福利）達成廣泛的認同，則繳稅會變成不是那麼痛苦的事情。若人們樂見其所承擔的金錢給付可以通過政府高效地轉化爲符合其意願的公共支出，非法避稅或逃漏稅的動機就會降低了。在一個稅捐遵從度較高的社會，稽徵成本可能會降低，公共財政的效率可能就會因此提升，從而人們對於政府財政效率的滿意度提升，比較不會對於不知道自己的稅金去哪了而憂心，也有利於稅捐遵從。這會是互為因果的。

因此，對於公共支出的分配，國家也有責任透過教育，讓國民有基本的判斷能力可以辨別是非利弊。例如，人民不會只依據自己的「看得到」、或者「拿得到」的東西，去判斷政府的執政服務能力或財政效率。更具體來講，對於馬路的重鋪、下水道系統的建設，民眾不會只因為重鋪馬路比較有直覺上的感知和獲益，而下水系統的維護改善可能不會有立竿見影的效果（但長期來看有助於增強地區對於極端降雨或洪澇災害的環境韌性）而因此更傾向於前者，從而間接讓政府部門偏好面子工程，不利於長期穩定發展。

進口蛋危機，對於台灣的民眾而言或許是極好的機會教育。隨著民眾關注到農委會在進口蛋事件上的失敗，進而意識到農委會對於進口蛋的補貼不公開，動用到農業發展基金或者經由貸款的方式支應雞蛋進口專案之所需，人們勢必開始質疑如此的公共支出是否基於恣意而未受足夠的專業監督。而面對這樣的信任危機，政府部門更應該將相關的資訊透明化，並且對於有監管漏洞的現行制度進行檢討，才能讓民眾和政府之間的關係維持在比較良性的循環。

---


## 第四週 柯格鐘

2023-09-26


在中國大陸，地方財政的問題目前主要體現在的地方債務危機，而究其根本原因，也就是失衡的中央地方財政劃分制度。不合理的財政制度，再加上地方對於發展規劃及行政上的的短視或急功近利，當地方無法通過正當的方式獲得收入滿足其公共支出之需求時，令人匪夷所思的事情就會發生：在國道設關卡逐車罰款、將程序員為境外公司工作之薪水認定為違法所得而全額沒收⋯⋯雖然這些離奇的事情是發生在一個法治不那麼健全的地方，但也值得引起台灣的關注，因為兩岸的地方財政所面臨的困境是類似的。當地方的財政壓力大到極點，地方為了籌措財源，不得不通過非常規手段去違反如今的財政體制的設計。若真到了那個地步，各地方一盤散沙，倒不如預先通過完整的財政體制改革，遵循財權事權之對應原則，為中央地方的財政權限做好重新的長期規劃。

老師認爲中央集權又集錢，造成資源分配極度不平均。

而地方稅作爲地方自治團體開拓財源之途徑，其開徵之可能性，除了訴諸法律層面的修訂，讓地方稅在項目、方式、期間等因素上面避免受到不必要的限制，更重要的還是通過整體的財政觀念教育，讓民衆普遍有長期的發展思維，

支離的財政法制體系會降低民衆對於政府治理能力與效率的信任。


古代的分封制，領主長久地對於地方治理

地方稅的項目、方式、期間的限制，本質上阻礙了地方通過課徵地方稅來擴種自主財源的可能。




## 第八周 廖欽福 公共債務 

2023-10-24

1. 課堂中討論到公債的法律關係的性質，提及了公法之債與私法之債之區辨。若以請求權時效的角度來看，會有不同的法律效果。依據行政執行法第 131 條規定，公法上請求權，因時效完成而當然消滅。如果在國家是債權人，人民是債務人的情景（如租稅事項），可以理解，是爲了保護人民。但在公債的情況，人民是債權人，政府是債務人，這時候，如果認爲是公法之債，時效完成之效果為請求權之當然消滅，是否適當？廖老師認爲偏向解釋爲私法上法律關係。而依據林老師的回應，如果解釋成公法上關係，不全然對於人民不利，因爲公債是基於政府信用，國家會有擔保責任。
然而，是否僅公法上之債才能夠有國家的擔保責任？個人認爲，定性爲私法上之債并不排除公債有國家信用的擔保。理由在於，國家之信用擔保是公債之本質，而公債之發行，并不如同其他公法上債務那樣地基於一方之行政高權的地位。特別當公法之債的定性可能會產生對人民更不利的法律效果時，應該解釋爲私法上之債為宜。

1. 如果將公債看作對於財政健全、財政紀律之破壞，
在租稅國家的理想之中，是否應全然摒棄公共債務之發行，或者是在某種特定的條件之下，對於特定類型的公共債務（例如建設公債），而允許發行？個人認爲，可以容許有條件地發行公共債務，例如僅發行用於重大基礎設施建設的公共債務。這樣的公共債務可能被認為是長期投資，有助於提高國家的生產力和競爭力。政府應該對於債務、預算、租稅制度進行整體評估，可以設定嚴格的監督機制，確保舉債不損害財政紀律，有助於長期的財政規劃。


## 第十周 論審計監督 呂理翔 

2023/11/07


機關職能，隨著時代變遷而改變，轉型

審計部管的事項涉及高度政治性的全國整體經濟方針，

過去一黨執政

權力分立之本質在於各機關的獨立而制衡

審計機關凌駕與民意機關之上？

審計機關以天下事為己任的狀況，

是否受到適當的制衡？

如果審計機關不是【獨立客觀公正】？

立法權要更强，除了在決算之審核的審議的程序，是否還有其他的階段應受到立法院的監督制衡？

師答：立法院的更强，除了通過對於審計部之監督而間接監督行政機關之決算，而更在於對於行政機關的直接監督。
