# 心得：回應同學報告

## 預算凍結

2023-10-03

謝謝同學報告，以下書面回應是我的問題部分

1. 行政機關之行爲與凍結事項之關聯性與可預期性
在預算凍結的決議中，對於凍結預算，行政機關要做成特定行爲、向立法院提出書面報告之後始得動支。在同學報告對於預算凍結的界限的討論部分，我認爲凍結的事由，似乎應該限縮為，可以訴諸于行政機關之行爲就能完成者。例如同學上課提到，立法院對於大版世博之參展名義，凍結經濟部國貿局首年預算1千萬元，並作成附帶決議，要求經濟部國貿局須爭取以台灣名稱參展。若立法院希望台灣能夠以台灣名義參展才解凍，則此事項并非僅有行政機關之努力即可達成，也就是説，行政機關即便積極地，也無法預期是否能夠達成正名的目的，則此時的預算凍結會隱含了條件的性質，還是否符合我們對於預算凍結之界定，值得討論。

2. 預算凍結與特定行爲之數額關係
同學報告中僅有提到對於預算凍結數額相對於預算數額之比例，卻沒有考慮到凍結事由之費用因素，以及與凍結數額之間的數額關係。
具體來講，在凍結事由中，若立法院希望行政機關做成特定行爲，假設此行爲是與該預算科目有合理的關聯性，而此特定行爲之執行需要一定的成本費用（先不討論如果此行爲也需要錢，那財源從哪裏來？），若此事項所需成本或隱含費用超出了預算凍結之數額，而行政機關基於種種考量，即可能沒有積極地完成此特定行爲之動機。在這種情況之下，雖爲預算凍結，卻無異於刪除預算之效果，其正當性應會有更大疑問。

3. 解凍
針對解凍程序，立法院是否還有一定的空間去如何評估行政機關對於特定行爲之達成率，一定是全額解凍嗎？再回到以上正名案例，決議中是否應該明確説明，只要行政機關在書面報告中説明其多麽積極地爭取正名，即可解凍，或者是，一定要努力有成果，爭取到可以台灣名義參展，才可以解凍？為避免爭議，凍結事由及解凍相關標準應於決議中明確表明。

## 決算 

2023/10/31

謝謝同學報告

1. p5. 關於地方與中央決算流程不同之部分，考慮到期限的差異、權衡立法機關對於決算之監督以及審計機關行使職權之獨立性，請問同學是否認同如此的設計？

2. p12-13 認爲，若容許立法機關要求提供原始憑證，有不尊重審計機關高度專業性之疑慮。是否可以請同學就此觀點展開詳述？若因擔心立法機關欠缺相關專業性而對原始憑證有不恰當的判斷或解讀，又應如何論述立法機關行使文件調閲權而要求調閲原始凴證之外的其他文件之正當性？是否是因爲原始憑證相較於各類文件，更容易受到不當解讀？個人認爲，不宜以是否原始凴證作爲區別的標準，而應該具體考慮特定的情形，依據立法機關的調閲的正當理由，衡酌審計機關或原機關之業務獨立性或相關的機密程度，而作更精細的標準。
3. 決算法28條第一項，若其立法理由是爲了鼓勵立法機關積極履行審議職權，則不宜有第二句逾期視爲通過之效果規定，因爲前後兩句在價值判斷上形成矛盾。應修改第二句為負面的法律效果，例如決算不生效力，或其他對於立法機關較爲不利的效果，方能實現對於立法機關積極審議之督促。

## 審計

謝謝同學報告

以下針對報告内容部分略有疑問，再請同學展開説明解答：

1. 報告p.9之處關於審計決定性質之分析，其中「至於通知命追繳之
部分，雖使權責機關之長官負有為追繳命令之行政法上義務，發生權力（利）義務之變動而有法律上效果，惟其乃係基於法律規定而生，而非基於審計機關之意思表示，故不具有拘束力。綜上，本案審計之決定，不符合對外發生公法上效果之要件，應非行政處分，將其定性為機關內部行文之實務見解，應較為可採。」其中所稱「拘束力」之意義爲何？
對應p.7底部的實務見解：「對各該應負責機關之長官具有法的拘束力」


以及同頁第三段中「惟此一見解忽略上開第三人權利義務之變動，均係基於法律規定而來，而非基於該審計決定，舉例言之，權責機關之長官之所以負有作成追繳命令之義務，乃係源於審計法第 78 條 1 項之規定，並非基於該審計決定而生，亦即審計決定不具有規制力，並非行政處分。」

若此内部行文依法律規定而對外使得機關長官負擔相應義務，是否仍然不具對外性？

謝謝同學！

---

師：決算法23

未明確區分合規性審查（合規與否）、績效性審查（效能）

## 公債（地方）

謝謝同學詳細介紹地方公債法制與實踐，我的問題如下：

1. p.12-13處，何爲「民主統制」？「民主統制之壓抑」之意義爲何？是側重於描述目前地方公債之審議欠缺民主正當性嗎？

2. 文中所提到的「地方財政健全指數」，係綜合各細項指標而得，可以對其進行縱橫向的比較分析，作爲評價地方財政健全之依據之一。但其結果并非一確切比例或數額，又應如何以此作爲具體計算地方政府舉債能力之界限？

3. 國家賠償法第 1 條：「本法依中華民國憲法第二十四條制定之。」又憲法第 24 條：「凡公務員違法侵害人民之自由或權利者，除依法律受懲戒外，應負刑事及民事責任。被害人民就其所受損害，並得依法律向國家請求賠償。」 文章p.16處所提及，逾越債限之公債發行之法律效果，可結合國家賠償法……想請教同學，爲何此處之發行行爲之相對人符合國家賠償法之要件？


## 公私協力 11/28

謝謝同學報告，我有想法如下

1. p.4.處有「...如合憲，進一步應探討立法者在擘劃租稅優惠時，對優惠目的、優惠相對人以及優惠效果，是否合乎平等原則之要求」，而下文内容在此部分似乎是針對「比例原則」進行討論，或爲筆誤？
2. 本案爭點，似乎與促參法無關？
見促參法第39條（地價稅、房屋稅、契稅之減免，0890114 制定）
參與重大公共建設之民間機構在興建或營運期間，供其直接使用之不動產應課徵之地價稅、房屋稅及取得時應課徵之契稅，得予適當減免。
前項減免之期限、範圍、標準及程序，由直轄市及縣（市）政府擬訂，提請各該議會通過後，報財政部備查。

又，臺北市促進民間機構參與重大公共建設減免地價稅房屋稅及契稅自治條例【中華民國93年11月15日臺北市政府(93)府法三字第09321432000號令制定】第4條：
民間機構參與本法第三條所定之本市重大公共建設，在興建或營運期間，**經主辦機關核定供直接使用之土地**，自稅捐稽徵機關核准之日起，地價稅免徵五年。
原經核准免徵地價稅之土地，於免徵期間未屆滿五年之前，移轉第三人繼續興建或營運者，准予免徵至五年期滿為止。

依據立法目的與體系，其中「供其直接使用之不動產」似乎應指本由此民間機構負擔納稅義務之不動產。個人認爲，係因民間機構可能是多筆土地之地價稅之納稅義務人，故在此限縮「供其（重大公共建設）直接使用之不動產」，且一土地是否「供直接使用之土地」，非由稅捐稽徵機關認定，而係由「主辦機關（臺大本人）核定」（進一步驗證，在此減免的是民間機構而非主辦機關的稅賦？）。


又土地稅法第 3 條
地價稅或田賦之納稅義務人如左：
一、土地所有權人。
二、設有典權土地，為典權人。
三、承領土地，為承領人。
四、承墾土地，為耕作權人。

顯見民間機構非系爭土地之納稅義務人，而系爭土地之地價稅之減免，自應無促參法相關規定之適用。

又見土地稅減免規則【民國 99 年 05 月 07 日】
第7條，第4項：
公立學校之學生宿舍，由民間機構與主辦機關簽訂投資契約，投資興建並租與該校學生作宿舍使用，且約定於營運期間屆滿後，移轉該宿舍之所有權予政府者，於興建及營運期間，其基地之地價稅得由當地主管稽徵機關專案報請直轄市、縣（市）主管機關核准免徵。

故，本案應無促參法第39條租稅優惠之適用。在本案，臺大主張促參法第39條、「臺北市促參自治條例」第4條，申請免納地價稅，個人認爲，是法律適用的錯誤。

而若臺大依據土地稅減免規則第7條第4項申請基地地價稅免徵，由於文本上并無「直接使用」之限制，較可能不會受到主管機關針對16、16-1號樓之否准。

---

參考：

促進民間參與公共建設法 
第 8 條

民間機構參與公共建設之方式如下：
一、民間機構投資新建並為營運；營運期間屆滿後，移轉該建設之所有權予政府。
二、民間機構投資興建完成後，政府無償取得所有權，並由該民間機構營運；營運期間屆滿後，營運權歸還政府。
三、民間機構投資興建完成後，政府一次或分期給付建設經費以取得所有權，並由該民間機構營運；營運期間屆滿後，營運權歸還政府。
四、民間機構投資增建、改建及修建政府現有建設並為營運；營運期間屆滿後，營運權歸還政府。
五、民間機構營運政府投資興建完成之建設，營運期間屆滿後，營運權歸還政府。
**六、配合政府政策，由民間機構自行備具私有土地投資興建，擁有所有權，並自為營運或委託第三人營運。**
**七、其他經主管機關核定之方式。**



公立大學以BOT方式興建學生宿舍之用地無免稅之適用
發文機關：財政部
發文字號：財政部 93.06.09.  臺財稅字第0930474296號
發文日期：民國93年6月9日
https://www.laws.taipei.gov.tw/law/LawInterpretation/LawInterpretationContent?soid=45465&typeName=%E8%B3%A6%E7%A8%85%E9%A1%9E
檢送研商「公立大學以 BOT 方式興建學生宿舍，有關該學生宿舍及其用地可否免徵房屋稅
及地價稅」相關事宜會議紀錄乙份。
附件：
研商「公立大學以 BOT 方式興建學生宿舍，有關該學生宿舍及其用地可否免徵房屋稅及地
價稅」相關事宜會議紀錄
本案公立大學將經管之國有土地，以 BOT 方式提供民間機構興建學生宿舍，興建完成後，
係由該民間機構所有及負責營運，因在學生宿舍興建及營運期間，公立大學對於民間機構將
收取租金或開發權利金或經營權利金，且在營運一段特定期間後，該學生宿舍係無償移轉與
學校所有，均認屬有收益之範疇。按此，有關該學生宿舍及其用地，應無國有財產法第 8
條免稅規定之適用；另學生宿舍興建完成後，因其建築物所有權係登記為民間機構所有而非
公有，亦無房屋稅條例第14條第 4款免徵房屋稅規定之適用。

