# 柯格鐘 地方財政

2023-09-26

流量、存量


1. 憲法上的財政基礎（107+109+110）
2. 法規範層次（規範密度較低）
3. 地方自治團體開拓自主財源的可能性與框架立法的問題（地方稅法通則）研究過少，地方爲什麽缺錢

## 憲法上的財政基礎（107+109+110+111）

<button type="button" class="collapsible">憲法上的財政基礎</button>
<div class="content">
  <p>

**第 十 章 中央與地方之權限**

第 107 條

> 左列事項，由中央立法並執行之：
> 
> - 一 外交。
> - 二 國防與國防軍事。
> - 三 國籍法及刑事、民事、商事之法律。
> - 四 司法制度。
> - 五 航空、國道、國有鐵路、航政、郵政及電政。
> - 六 中央財政與國稅。
> - **七 國稅與省稅、縣稅之劃分。** 【關鍵權力】
> - 八 國營經濟事業。
> - 九 幣制及國家銀行。
> - 十 度量衡。
> - 十一 國際貿易政策。
> - 十二 涉外之財政經濟事項。
> - 十三 其他依本憲法所定關於中央之事項。

---

第 108 條

> 左列事項，由中央立法並執行之，或交由省縣執行之：
> 
> - 一 省縣自治通則。
> - 二 行政區劃 。
> - 三 森林、工礦及商業。
> - 四 教育制度。
> - 五 銀行及交易所制度。
> - 六 航業及海洋漁業。
> - 七 公用事業。
> - 八 合作事業。
> - 九 二省以上之水陸交通運輸。
> - 十 二省以上之水利、河道及農牧事業。
> - 十一 中央及地方官吏之銓敘、任用、糾察及保障。
> - 十二 土地法。
> - 十三 勞動法及其他社會立法。
> - 十四 公用徵收。
> - 十五 全國戶口調查及統計。
> - 十六 移民及墾殖。
> - 十七 警察制度。
> - 十八 公共衛生。
> - 十九 振濟、撫卹及失業救濟。
> - 二十 有關文化之古籍、古物及古蹟之保存。
> 
> 前項各款，省於不牴觸國家法律內，得制定單行法規。

---

第 109 條

> 左列事項，由省立法並執行之，或交由縣執行之：
> 
> - 一 省教育、衛生、實業及交通。
> - 二 省財產之經營及處分。
> - 三 省市政。
> - 四 省公營事業。
> - 五 省合作事業。
> - 六 省農林、水利、漁牧及工程。
> - 七 省財政及省稅。
> - 八 省債。
> - 九 省銀行。
> - 十 省警政之實施。
> - 十一　省慈善及公益事項。
> - 十二　其他依國家法律賦予之事項。
> 
> 前項各款，有涉及二省以上者，除法律別有規定外，得由有關各省共同辦理。
> 
> 各省辦理第一項各款事務，其經費不足時，經立法院議決，由國庫補助之。

---

第 110 條

> 左列事項，由縣立法並執行之：
> 
> - 一　縣教育、衛生、實業及交通。
> - 二　縣財產之經營及處分。
> - 三　縣公營事業。
> - 四　縣合作事業。
> - 五　縣農林、水利、漁牧及工程。
> - 六　縣財政及縣稅。
> - 七　縣債。
> - 八　縣銀行。
> - 九　縣警衛之實施。
> - 十　縣慈善及公益事項。
> - 十一　其他依國家法律及省自治法賦予之事項。
> 
> 前項各款，有涉及二縣以上者，除法律別有規定外，得由有關各縣共同辦理。 

---

第 111 條

除第一百零七條、第一百零八條、第一百零九條及第一百十條列舉事項外，如有未列舉事項發生時，其事務有全國一致之性質者屬於中央，有全省一致之性質者屬於省，有一縣之性質者屬於縣。遇有爭議時，由**立法院**解決之。  
</p>
</div>
<br>

## 法規範層次

<button type="button" class="collapsible">財政收支劃分法 37+38 條 【對應原則】 財權隨事權劃分及**移轉**</button>
<div class="content">
  <p>

第 37 條

1. 各級政府之支出劃分如下：

- 一、由中央立法並執行者，歸中央。
- 二、由直轄市立法並執行者，歸直轄市。
- 三、由縣（市）立法並執行者，歸縣（市）。
- 四、由鄉（鎮、市）立法並執行者，歸鄉（鎮、市）。
2. 前項第一款及第三款如需交由下級政府執行者，其經費之負擔，除法律另有規定外，**屬委辦事項者，由委辦機關負擔**；屬自治事項者，由該自治團體自行負擔。
3. 由中央或直轄市、縣（市）、鄉（鎮、市）二以上同級或不同級政府共同辦理者，其經費應由中央或各該直轄市、縣（市）、鄉（鎮、市）按比例分擔之。
4. 各級地方政府未依第二項及前項規定負擔應負擔之經費時，其上級政府得扣減其補助款。

---

第 38 條

各級政府事務委託他級或同級政府辦理者，其經費由委託機關負擔。
</p>
</div>
<br>

特別公課就有財權移轉的問題，特別公課都是中央在立法徵收，但事情是地方在做，沒得分錢？


<button type="button" class="collapsible">財政收支劃分法 38-1 條 補充財源</button>
<div class="content">
  <p>

第 38-1 條

各級政府、立法機關制（訂）定或修正法律或自治法規，有減少收入者，應同時籌妥替代財源；需增加財政負擔者，應事先籌妥經費或於立法時明文規定相對收入來源。

</p>
</div>
<br>


## 地方自治團體開拓自主財源的可能性與框架立法的問題

自主財源，基準財政需要

地方的基準財政能力要對應到他的基準財政需要。
財政平衡制度的目的：能力不足以支應需要（公共服務要有基本水準）？從財政平衡制度中獲取一些。

體制的扭曲分配

地方稅法通則是否可以讓地方開拓稅收？

特別稅，4年+4年，跟地方首長的任期一致，一上任立刻推動加稅，要會有連任的選票嗎？政治人物一般不會去推動得罪選民的加稅。除非是對於政治不正確的少數對象（砂石業者、礦石業者、特種營業業者）。特殊地理條件，靠山吃山，靠海吃海？不太容易。政治難度較高。

短期少量，無法支應長久的地方財政需求。

這種框架立法實質上限制了地方開拓自主財政收入的可能。

地方缺錢，本質上是跟整個法秩序對於地方財政收入不太有利相關。


地方特別公課是來自於事務高權（權限來源是地方制度法），而非財政高權。夾在中央與人民之間。

雲林縣曾經想要課徵碳費，一樣是要錢，非以稅爲名，是否可以繞過地方稅法通則的限制？這有沒有道理？人民一定會反抗到底。


沒有有效的制度去控制特別公課的徵收和使用。