# 特種基金


2023-10-17

陳老師建議：

1. 前言的部分不用拆開成三部分，用一個前言即可，帶出問題意識
2. 不必特別列出專節作文獻整理
3. 文章要有轉折，不用一開始就指明自己立場采用指定用途稅
4. 特種基金合法性：財政紀律8（3）

標題的建議

不要一開始就説應該費改稅

從426去討論作爲特別公課的合法性

預算法、會計法、財政紀律法8

法律保留原則的兩種理論：

1. 【法律保留原則，重要性理論】 重要的事項應該由法律規範
   1. 預設，立法者管的要是比較重要的，跟基本權利、公共利益密切相關之事項；反之，比較技術性、細節性的事項，可以交給行政機關。
2. 【機關功能最適理論】重要的事項，如果跟專業性有關的，也有可能歸給行政機關。

要分開來談，不同的理論的推導。

若改采指定用途稅，要適用的法律保留原則，是跟一般的租稅一樣的嚴格，還是仍然采取較寬鬆呢？

---

引用資料格式要遵照臺大法學論叢。

引用網路資料，要標明「造訪日期」

注脚的「同前注」，要標明作者

文末參考文獻，網路資料不要放法條、函釋、大法官解釋


----

12/05 課後 問陳老師，陳老師答

1. 報告的標題，初稿的標題過於冗長，改用「非營業特種基金制度研究——以空氣污染防制基金為例」，是否合適？
   - 標題改以：空氣污染防制基金之制度研究 （因爲内文聚焦於空污基金，不用小孩穿一件很大的衣服）
2. 文中引用學者見解，是否不要在本文指明學者姓名（我有在正文中寫明學說見解之學者姓名，報告時，林老師針對這部分作了批評）？
   - 都可以。不在正文中指明姓名，則用：有學者認爲，亦有學者持。。。觀點，另有學者指出
3. 張永明老師在《財政法》專書中的文章，是和大致同時間發表在期刊（財稅研究）上的内容非常接近！在標注引用文獻時，應該如何引用？
   - 沒關係，（如果只引用期刊，就會少了專書的引用？）沒關係的
4. 柯老師引用德國法院見解，我又引用柯老師的文章，應如何恰當標注？
   - 【陳】：因爲不是直接的自己去看了的引用，就在注脚中標明，德國某法院之實務見解，是引用自柯老師的文章、書籍。
   - 【柯】：不是直接閲讀，就不要直接引用。跳過前一手，直接引用原文，是學術倫理的問題。你有那本書嗎？那本書只有我有！有次政大的某論文，第一個注脚，就寫a.a.o.（同前注）（XDDD
   - 【柯】：引誰的文獻，誠實以對。論文是你的孩子，沒有寫好，就變成嬰霛。
5. 老師在報告後評論提到，前言不必用這三個部分的小節，但我感覺我的前言的内容確實區分爲了這三個部分，包含注脚有三頁多，是否還是加上小標題比較適當呢？
   - 今後成爲學位論文之一部分，可保留。
6. 是否在文章摘要部分不要提前顯露本文見解立場（建議改指定用途稅）？
   - 可以表明。開門見山的寫作方法。另有一種寫作類型，是在前部分抛出問題，不直接表明見解。
7. 老師提到用財政紀律8（3）去檢視空污基金之合法性。但是財政紀律8（3）僅向後生效，應如何適用？ 且合法性管控之具體内容已具體在3、4章詳述~
   - 可在前言部分提及財政紀律8（3），將思考過程顯示出來，爲何本文不討論某問題，限縮討論範圍。
8. 財源的部分，老師希望文章小節的3-1叫污染者付費，與3-2的環保署撥補對應，但是3-1空氣污染防制費中另有專節討論污染者付費原則在空污費中的適用，似乎會重複標題~
   - 沒問題。