# 論審計監督 呂理翔

2023/11/07


## 如何理解審計權

財政監督之權力，屬於監察院或立法院？民意代表？

責任歸屬？

行政權v.s.監查權


## 審計部管得很寬

管了很多行政的事情，這些都歸他管嗎？不能説完全沒關係，這些活動都跟預算執行有關係，但毋寧是跟行政機關的上級機關或立法院的職權相關。


地方財政的監督，也由中央的審計部行使？

釋字235（1989）合憲，憲增7


地方自治之事項，不包含財政執行之監督

---

地方制度法§42-

直轄市、縣（市）決算案，應於會計年度結束後四個月內，提出於該管審計機關，審計機關應於決算送達後三個月內完成其審核，編造最終審定數額表，並提出決算審核報告於直轄市議會、縣（市）議會。總決算最終審定數額表，由審計機關送請直轄市、縣（市）政府公告。直轄市議會、縣（市）議會審議直轄市、縣（市）決算審核報告時，得邀請審計機關首長列席說明。
鄉（鎮、市）決算報告應於會計年度結束後六個月內送達鄉（鎮、市）民代表會審議，並由鄉（鎮、市）公所公告。

---

回到國父的構想

是否能夠落實？

釋字81（1958）
審計部的超然地位，立於財政（行政權）之外，

釋字46/釋字184

【行政、立法、審計 的三角關係】

審計部（審定決算書時）有權剔除不合法的收支，不受原始凴證之拘束

【Q】是否可以救濟？何時可以救濟？

最終通知到特定個人（實際負責人），而命補繳之程序（行政處分）

會不會太晚？ 【多階段行政處分】

## 國外的審計機關之定位

美國 後來才從行政獨立出來

德國：三權之外的獨立機關

## 政府采購：事前稽查改爲隨時稽查

派駐（審計機關派駐行政機關） 改爲 隨時派員

1990年代，政府行政機關内部人員（主計、財會）的審計能力提高了

## 審計部門職能重心轉型：促進政府良善施政治理

只是警告、建議，
并沒有法律上的拘束力，但有事實上的拘束力，
在行政慣例上不會跟審計部提出反面的意見


審計法和決算法的内容交錯，大量涉及對方的權限

審計機關的權限，涉及高度政治性的，全國總體經濟，歲入歲初，整體施政方針，
毋寧更適合由立法院（民意機關）而行駛此類職權？

立法院的逾期視同通過，體現了立法院的弱勢？

## 心得

機關職能，隨著時代變遷而改變，轉型

審計部管的事項涉及高度政治性的全國整體經濟方針，

過去一黨執政

權力分立之本質在於各機關的獨立而制衡

審計機關凌駕與民意機關之上？

審計機關以天下事為己任的狀況，

是否受到適當的制衡？

如果審計機關不是【獨立客觀公正】？

立法權要更强，除了在決算之審核的審議的程序，是否還有其他的階段應受到立法院的監督制衡？

師答：立法院的更强，除了通過對於審計部之監督而間接監督行政機關之決算，而更在於對於行政機關的直接監督。

---

師：退居立法權、行政權之後，

從立法過程來看，審計法是由審計部主導

期待立法權更强一點

機關和機關之間是沒有行政處分的，不會對外產生規制效果

審計機關還覺得自己的職權不夠，

【momo評：以天下事爲己任XDD】

---

【林】財政法是數政之母

立法政策不是法律人的擅長

立法院沒有能力去執行預算、決算的監督，沒有專業知識

---


【陳】

審計機關之權限過寬，是由於法律上給了它很大的空間

行政執行之合法性由審計部監督，適當性則回歸由上級機關之監督


---

同學：審計法78條

司法與審計之互動

合規審計之法律監督之加强