# 特別公課之概念及與稅捐的區別




## 柯老師^[特別公課之概念及爭議－以釋字第四二六號解釋所討論之空氣污染防制費為例]

特別公課與稅捐之區別標準

- 不在於是否對於特定群體或者一般人民進行課徵而有區別。
  - 例如，菸酒稅也只對於抽煙喝酒之人課徵，但從無人懷疑該等公課為稅捐之性質。娛樂稅也只對於從事特定娛樂行為之人課徵，從無人質疑其屬稅捐之性質。即使是所得稅，也只對於所得到達一定額度之人課徵，卻也從無人認為此種金錢負擔義務之性質為特別公課；
- 也不在於所獲得之收入是編入特種基金或是一般國庫中運用而有區別。
  - 蓋因為編入特種基金或國庫財政，僅為形式上的選擇與差異^[Jarass, a.a.O.（Fn.25）, S. 1017]，將本質上為稅捐的財源收入，以特別公課之外觀形式編入特種基金中運作，其形式上的錯誤不代表實質本質的改變；
- 也不在於其以引導公課義務人之行為為目的或以財政收入為目的進行課徵而有區別。
  - 蓋無論是特別公課或稅捐，性質上均有財政收入目的與引導目的之公課類型^[Vgl. Lang, a.a.O.（Fn. 22）, § Rz. 28 f.]。
- 特別公課與稅捐之區別，**主要在於公課徵收之目的**，亦即特別公課是為了公課義務人之「群體用益性」為目的而徵收，而稅捐之徵收則是為了一般公眾之利益，用以執行與一般公眾利益有關之公共任務^[arass, a.a.O.（Fn.25）, S. 1017]。
 
因此，在承認特別公課槪念之前提下，特別公課之徵收或者是為了取得為完成對於共同義務人群體有共同利益（群體用益性）之公共任務，或者是為了取得照顧公課義務人群體對之有共同社會責任（群體有責性）之受益人群體的公共任務所需財源，在此種意義下即為公課義務人群體對之有共同利益（群體用益性）的公共任務，為了取得完成上述任務之公共財源而徵收的公課即為特別公課。反之，為了完成以一般公眾利益之目的為公共任務而徵收的公課，或者公課義務人群體與受益人群體之間並無任何特殊之事物關聯性時，只要其所課徵公課之收入係用於完成上述事項之公共任務，則其公課之性質即應論為稅捐例如，前述對於赴大陸投資台商加徵「國安捐」之建議，若徵收「國安捐」所獲之財源，係指定用於增加國防預算者，此種公課性質上可謂係基於一般公眾利益而徵收之稅捐，因其徵收時即指定用途，故為學說上所稱之目的稅；又如，前述衛生署打算對於嚼食檳榔之人加徵之「檳榔健康捐」，其徴收「檳榔健康捐」所增加之收入，據信將指定用於挹注健保局之健保費收入。果真如此，則徵收此等公課的義務人群體與受益人群體並無事物關聯性者，亦即嚼食檳榔之人對於長期使用健保資源之病患並無特殊之社會責任存在，其所繳納檳榔健康捐之公課性質亦應屬於稅捐。因其徴收時即指定特定之使用用途，故為目的稅；同理，對於油（燃）料使用者徴收之空氣污染防制費，若其收入係用於改善空氣品質者，因改善空氣品質顯係基於一般公眾之利益，故支應完成此種公共任務之公課應為稅捐。因其徵收時即已指定用途，故為目的稅。

## 蔡茂寅^[財政法：第四講　原因者付費制度（下）]

特別公課具有「為政策目標限定其用途」、以及「向有特定關係之國民課徵」等特色。論者有謂，特別公課乃指「為完成經濟行政領域的特殊任務，而對特定群體賦予特殊的金錢給付義務，其收入亦流向特定之用途」^[何愛文，特別公課（Sonderabgaben）之研究－現代給付國家新興之財政工具，臺大法研所碩士論文，1994年，11 頁。]。

特別公課之概念特徵包括：

- 一、特別公課之課徵可能是為了追求特定之經濟或社會目的，而不僅限於財政上之效果。
- 二、特別公課是用來實現特別的任務；相較於一般的納稅大眾而言，特別公課的負擔義務人與該特別的任務間有較密切的關聯。
- 三、對於特別公課的繳納義務人而言，國家不需為相對應的對待給付。
- 四、特別公課之課徵是以「特殊的法律上關聯」為出發點，亦即，金錢給付義務與負擔理由之間須存在「特殊的法律上關聯」，此種「特殊的法律上關聯」也成為其合法性之要求。

上述一、主要係用來與稅公課相區別；然而吾人亦不能否認稅公課除財政目的性外，亦往往兼具經濟或社會目的性，因此，此等區別毋寧僅係量的區別，而非質的差異。
上述二、主要亦係用來與稅課相區別。然而此等特徴其實為本講所述之非稅公課（受益負擔與特別公課）之共同特徵，因此其作為槪念特徴之判準性仍屬不足。抑且，如限定在所謂之目的稅（或指定用途稅），由於其任務特定性明確，因此僅執任務特定性似仍不足以作為區別特別公課與稅公課之判準。
上述之三、為與稅公課共有之特徴，因此其功能主要在作為與受益負擔間之判準。
上述之四、主要為與稅公課相區別之特徵，然而「特殊的法律上關聯」云云者，細究之實則為所有旳非稅公課手段所共有之特徵，因此其作為判準之特定性仍屬不足（此亦為本文主張應將非稅公課名之為「原因者付費」之理由所在）。

質言之，特別公課由於係為特定目的（完成特殊任務）、向特定群體所課徵之特殊的公法上金錢給付義務、其用途亦屬特定。此等特定性一方面雖使其足以與稅公課相區別，但在另一方面則尚難構成與其他非稅公課區別之特徵。例如「對待給付性（「對價性」）雖然為受益負擔之特徴，但除此之外之其他公課亦不具該等性質，因此「非對價性」僅足作為與受益負擔區別之判準，而無法據以區別特別公課與其他公課（乃至稅公課）。又例如用途限定性即為特別公課與受益費所共有之特徵，凡此均足證明特別公課在概念上仍欠缺成熟性。以下略述特別公課與其他公課之區別。

### 特別公課與稅課之區別

職是之故，「特別公課與稅捐不同，稅捐係以支應國家普通或特別施政支出為目的，以一般國民為對象，課稅構成要件須由法律明確規定，凡合乎要件者，一律由稅捐稽徵機關徵收，並以之歸入公庫，其支出則按通常預算程序辦理」（同號解釋理由書）。故謂，特別公課有別於一般稅捐，其課徵非在滿足一般之公共財政需求，而是有其特殊之形成性功能，其收入乃多流向特種基金，使用在特定用途上^[參照何愛文，22 頁。]，與前述稅捐之財政目的屬一般者不同，可謂是特殊之財政目的。論者謂特別公課之合法性標準中有一為，特別公課「不得為獲得公法人團體的一般財政需要的收入目的，而加以徵收，且其收入不得被使用於支應一般的國家任務之財政需要，（所謂並無一般負擔的形式的特別公課）」^[參照陳清秀，稅法總論，元照，2010 教新版，2010 年，79 頁。]，故可顯示其特殊之財政目的。

易言之，稅課與特別公課之差異，在於稅之課徵對象為一般社會大眾，目的在於滿足一般之公共財政需求，納入公共預算中，而特別公課乃納入特種基金^[目的稅與特別公課仍可區分，蓋目的稅乃是某項税捐的收入限定特定的目的支出，而目的稅的繳納義務人不限於經濟上得享受國家特定作為利益之人。參照何愛文，22 頁。]中。惟稅課中亦有所謂的「指定用途稅」，其用途在徵收之初即已特定，因而亦需編入特種基金，而非以普通基金之型態存在，據此言之，特別公課作為公課之一種，其與稅課之區別並不明顯^[有謂：「特別公課與目的税不同之處，在於特別公課就其課徵金額係與國家所給予利益之費用或使用相連結；反之，目的稅則無此種關聯性」。參照陳清秀，79 頁。]，有之，則應求之於「特定關係」。然而所謂「特定關係」者，在界定上本即十分困難，例如上揭空氣污染防制費，固不妨以稅課方式徵收之，甚至採用附加捐之方式亦無妨，故可知上揭判準之實踐意義不大。此蓋由於租稅之義務人通常固以一般國民為對象，但某種程度限定其範圍並非法所不許，例如菸酒稅附加之健康捐，即符合特定關係、為政策目標限定用途及特種基金等要件，但其以稅捐之形式存在，亦不被質疑其合法性及妥當性，可為明證。